### ISSUE TITLE
Long strings do not fall in next line automatically, hence making tree very large. 

### ISSUE THREAD

**Issue by vivekmehtaindore** [browneyedsoul/RemNote-RemTree#3]
![image](https://user-images.githubusercontent.com/119961995/205976929-265565c5-00c3-4b1b-942c-f59825285d58.png)

**Comment by browneyedsoul** [comment]
Give it a try this.
apply this css snip on top of your tree 

```css
.rn-editor-container [data-rem-container-tags~=tree] .whitespace-pre-wrap {
  white-space: pre-wrap;
}
```
